# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Create App"
  lane :create_app do
    create_app_online # produce
  end

  desc "Sync signing"
  lane :signing do
    sync_code_signing # match

    # mapping = Actions.lane_context[
    #   SharedValues::MATCH_PROVISIONING_PROFILE_MAPPING
    # ]
    #
    # update_code_signing_settings(
    #   profile_name: mapping[ENV['MATCH_APP_IDENTIFIER']]
    # )
    # add actions here: https://docs.fastlane.tools/actions
  end

  desc "Build"
  lane :build do
    # add actions here: https://docs.fastlane.tools/actions
  end

  desc "Release"
  lane :release do
    # add actions here: https://docs.fastlane.tools/actions
  end
end
